### ISSUE TITLE
Address not showing in active miners

### ISSUE THREAD

**Issue by Gaboswiss** [justino/p2pool-ui-punchy#7]
Hi, I've been mining for two days and my address is not showing in the active ones, ever... I've tried with two addresses, checked the firewall, and a long etc... 
Maybe I'm doing something wrong? The address is XdENc3MSyJa4LVvnAH8EPQUGXYinbxUL7T

Thanks,
G.

**Comment by justino** [comment]
I can't speak too much about the why of it, but this UI queries p2pool directly and asks it for it's list of miners, either one of two things is happening.

1) p2pool isn't responding back with the mining address
2) It's responding back, but this UI doesn't know how to interpret the response correctly.

Do you have a link to the p2pool so I can check out the JS console?

**Comment by Gaboswiss** [comment]
Hi Justin, the pool is//185.136.89.182:7903 I've been mining nonstop since now 5 days and still nothing.... :-(

**Comment by justino** [comment]
So, just looking at this from the outside. I would say your miner isn't working.
You can ask the pool itself (without going through the UI) for a list of active miners: http://185.136.89.182:7903/local_stats and your address isn't in the list it returns.

So either your miner isn't working, your miner is mining on a different pool, or something else is wrong. None of which I can help with.

Since you are the one asking here, I am assuming it's your p2pool node. Check the p2pool logs for any info on that address that might help shed some light on what is going on.

**Comment by Gaboswiss** [comment]
I did that, and tried several suggestions offered in the forums, apparently there's lots of guy having similar issues. Opening port 8999 also did not work.  Anyways thank you for helping.  I stopped the miner to give my computer a rest.  I'll re-try with another pool later on.
